package authclient

import (
	"fmt"
	"os"
	"strings"
	"time"
)

// SaveToEnvFile は認証レスポンスを.envファイルに保存します
func (resp *VerifyResponse) SaveToEnvFile(filename string) error {
	var content strings.Builder

	// ヘッダー
	content.WriteString("# Generated by go_auth\n")
	content.WriteString(fmt.Sprintf("# Timestamp: %s\n\n", time.Now().Format(time.RFC3339)))

	// JWTトークン
	content.WriteString(fmt.Sprintf("AUTH_TOKEN=%s\n", resp.Token))

	// Secret変数
	if len(resp.SecretData) > 0 {
		content.WriteString("\n# Secret Data\n")
		for key, value := range resp.SecretData {
			content.WriteString(fmt.Sprintf("%s=%s\n", key, value))
		}
	}

	// ファイルに書き込み（パーミッション: 0600）
	if err := os.WriteFile(filename, []byte(content.String()), 0600); err != nil {
		return fmt.Errorf("failed to write .env file: %w", err)
	}

	return nil
}

// SaveToEnv はデフォルトの.envファイルに保存します
func (resp *VerifyResponse) SaveToEnv() error {
	return resp.SaveToEnvFile(".env")
}
